export const calendarData = [
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный прием",
        "header": "Предварительный приём-1",
        "text": null, //"Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": null,
        "warning": false,
        "link": null,
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Категория-2",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Категория-3",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Категория-4",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Категория-5",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Категория-6",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Категория-7",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
]