export const calendarData = [
    {
        "month": 6,
        "number": 4,
        "timeStart": "18:00",
        "timeEnd": "19:00",
        "category": "Категория-5",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 6,
        "number": 4,
        "timeStart": "09:00",
        "timeEnd": "19:00",
        "category": "Категория-6",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 6,
        "number": 4,
        "timeStart": "10:00",
        "timeEnd": "17:00",
        "category": "Категория-4",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": true,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 6,
        "number": 4,
        "timeStart": "17:00",
        "timeEnd": "18:00",
        "category": "Категория-3",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": true,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": false
    },
    {
        "month": 6,
        "number": 4,
        "timeStart": "08:00",
        "timeEnd": "18:00",
        "category": "Категория-10",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": true
    },
    {
        "month": 6,
        "number": 4,
        "timeStart": "07:00",
        "timeEnd": "18:00",
        "category": "Категория-11",
        "header": "Предварительный приём-1",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Базовое высшее",
        "primary": true
    },

]