import {ICalendarDay} from "./components/calendar-app";

export const CalendarData : Array<ICalendarDay> = [
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Все"
    },
    {
        "month": 4,
        "number": 2,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Компьютерные науки и прикладная математика»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "Базовое высшее"
    },
    {
        "month": 4,
        "number": 3,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Специализированное высшее"
    },
    {
        "month": 4,
        "number": 2,
        "timeStart": "",
        "timeEnd": "",
        "category": "Завершение",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Специализированное высшее"
    },
    {
        "month": 4,
        "number": 3,
        "timeStart": "",
        "timeEnd": "",
        "category": "Мероприятие",
        "header": "Вручение подарков",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Специализированное высшее"
    },
    {
        "month": 4,
        "number": 4,
        "timeStart": "",
        "timeEnd": "",
        "category": "Мероприятие",
        "header": "Вручение подарков",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Специализированное высшее"
    },
    {
        "month": 4,
        "number": 4,
        "timeStart": "",
        "timeEnd": "",
        "category": "Мероприятие",
        "header": "Вручение подарков",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Специализированное высшее"
    },
    {
        "month": 4,
        "number": 5,
        "timeStart": "",
        "timeEnd": "",
        "category": "Мероприятие",
        "header": "Вручение подарков",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Специализированное высшее"
    },
    {
        "month": 4,
        "number": 6,
        "timeStart": "",
        "timeEnd": "",
        "category": "Мероприятие",
        "header": "Вручение подарков",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "Специализированное высшее"
    },
]