import {CalendarDay} from "./components/calendar-app";

export const CalendarData : Array<CalendarDay> = [
    {
        "month": 2,
        "number": 31,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 30,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 29,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 28,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 27,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 26,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 25,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 24,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 23,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 22,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 21,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 20,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 19,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 18,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 17,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 16,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 15,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 14,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 13,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 12,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 11,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 10,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 9,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 8,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 7,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 6,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 5,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 4,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 3,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 2,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 2,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 19,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 18,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 17,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 16,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 13,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 12,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 11,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 10,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 9,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 6,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 5,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 4,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 3,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 2,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 30,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 29,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 28,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 27,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 26,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 23,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 22,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 21,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 20,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 19,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 16,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 15,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 14,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 13,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 12,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 11,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 10,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 9,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 8,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 7,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 6,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 5,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 4,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 3,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 2,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 30,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 29,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 28,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 27,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 26,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 25,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 24,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 23,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 22,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 21,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 20,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 19,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 18,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 17,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 16,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 15,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 14,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 13,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 12,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 11,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 10,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 9,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 8,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 7,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 6,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 5,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 4,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 15,
        "timeStart": "10:00",
        "timeEnd": "14:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 14,
        "timeStart": "16:00",
        "timeEnd": "19:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 8,
        "timeStart": "10:00",
        "timeEnd": "14:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 7,
        "timeStart": "16:00",
        "timeEnd": "19:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 1,
        "timeStart": "10:00",
        "timeEnd": "14:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 31,
        "timeStart": "16:00",
        "timeEnd": "19:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 25,
        "timeStart": "10:00",
        "timeEnd": "14:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 24,
        "timeStart": "16:00",
        "timeEnd": "19:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 18,
        "timeStart": "10:00",
        "timeEnd": "14:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 4,
        "number": 17,
        "timeStart": "16:00",
        "timeEnd": "19:00",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн / Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 20,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Авиастроение» и «Передовой инженерной школы»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 3,
        "number": 6,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Двигателестроение»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 3,
        "number": 13,
        "timeStart": "10:00",
        "timeEnd": "",
        "category": "День открытых дверей",
        "header": "День открытых дверей: перейди на новый уровень",
        "text": "13 апреля Московский авиационный институт проведёт масштабный день открытых дверей для поступающих на программы базового высшего образования, бакалавриата и специалитета с участием всех институтов. Вы сможете получить полную информацию об университете и образовательных программах МАИ, узнать о правилах поступления в 2024 году, пообщаться с руководством и специалистами МАИ.",
        "location": "Дубосековская, 4а, стр.1 (ДКиТ МАИ) / Вконтакте",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177111",
        "degree": "bachelor"
    },
    {
        "month": 2,
        "number": 30,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Информатика, кибернетика и электроэнергетика»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 2,
        "number": 16,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Радиоэлектроника и системы связи»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 2,
        "number": 2,
        "timeStart": "13:00",
        "timeEnd": "14:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей «Института иностранных языков»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 2,
        "number": 2,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей института «Экономика и менеджмент высокотехнологичной индустрии»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 1,
        "number": 17,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Ракетно-космические системы»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": null,
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 0,
        "number": 20,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Материалы и современные технологии»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 3,
        "number": 3,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 2,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 3,
        "number": 1,
        "timeStart": "",
        "timeEnd": "",
        "category": "Предварительный приём",
        "header": "Предварительный приём ",
        "text": "Предварительная подача документов в приёмную комисcию и индивидуальные консультации по поступлению в МАИ в 2024 году.",
        "location": "Онлайн ",
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login",
        "degree": "all"
    },
    {
        "month": 5,
        "number": 20,
        "timeStart": "14:00",
        "timeEnd": "17:00",
        "category": "Приём документов",
        "header": "Официальное начало приёма документов",
        "text": null,
        "location": null,
        "warning": false,
        "link": "https://lk.mai.ru/accounts/login/",
        "degree": "all"
    },
    {
        "month": 1,
        "number": 3,
        "timeStart": "10:00",
        "timeEnd": "15:30",
        "category": "День открытых дверей",
        "header": "День открытых дверей — выставка предприятий в МАИ",
        "text": "В мероприятии примут участие около 60 ведущих предприятий высокотехнологичной и IT индустрии — крупнейших организаций, входящих в состав ГК «Ростех» и «Роскосмос», корпораций «Объединённая авиастроительная корпорация», «Объединённая двигателестроительная корпорация», «Вертолёты России», Корпорации «Тактическое ракетное вооружение», Концерна ВКО «Алмаз — Антей», VK, Ростелеком и других. Школьники и их родители смогут узнать об условиях работы на рынке высоких технологий, об особенностях и перспективах целевой формы подготовки, а также проектах и разработках, в которых смогут принять участие будущие студенты и выпускники МАИ.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177109",
        "degree": "bachelor"
    },
    {
        "month": 1,
        "number": 10,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Робототехнические системы и комплексы вооружения летательных аппаратов»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    },
    {
        "month": 0,
        "number": 27,
        "timeStart": "11:00",
        "timeEnd": "12:00",
        "category": "День открытых дверей",
        "header": "День открытых дверей меганаправления «Компьютерные науки и прикладная математика»",
        "text": "Абитуриенты и их родители смогут получить полную информацию о том, чему учат на меганаправлении, об образовательных и карьерных траекториях, целевой подготовке, практике, стажировках и внеучебной жизни, а также пообщаться с руководством институтов МАИ и задать свои вопросы.",
        "location": "Волоколамское шоссе, 4к6",
        "warning": false,
        "link": "https://priem.mai.ru/news/item.php?id=177110",
        "degree": "bachelor"
    }
]